// components/socialBar.vue
<template>
    <div class="mx-auto rounded-t-lg shadow bg-gray-900 sticky bottom-0 w-full py-1">
        <p class="text-center text-white">ติดต่อได้ที่</p>
        <div class="mx-auto max-w-screen-xl px-4 flex justify-center items-center w-full h-full">
            <div class="flex-shrink-0 flex items-center space-x-4">
                <a v-for="social in socials" :key="social.id" :href="social.href">
                    <svg class="transition-transform duration-300 hover:scale-150" xmlns="http://www.w3.org/2000/svg"
                        x="0px" y="0px" width="50" height="50" viewBox="0 0 50 50">
                        <path :fill="social.fill1" :d="social.d1"></path>
                        <path :fill="social.fill2" :d="social.d2"></path>
                        <polygon :fill="social.polyfill" :points="social.pointpolly"></polygon>
                        <path :fill="social.fill3" :d="social.d3"></path>
                        <path :fill="social.fill4" :d="social.d4"></path>
                    </svg>
                </a>    
            </div>
        </div>
    </div>
</template>
<script setup lang="ts">
function getRandomNumber() {
    const number = ["tel:0649370011", "tel:0649370033", "tel:0649370066"];
    const randomIndex = Math.floor(Math.random() * number.length);
    return number[randomIndex];
}
const socials = [
    {
        id: 1,
        href: 'https://www.facebook.com/RSTrophy01',
        fill1: '#039be5',
        d1: 'M24 5A19 19 0 1 0 24 43A19 19 0 1 0 24 5Z',
        fill2: '#fff',
        d2: 'M26.572,29.036h4.917l0.772-4.995h-5.69v-2.73c0-2.075,0.678-3.915,2.619-3.915h3.119v-4.359c-0.548-0.074-1.707-0.236-3.897-0.236c-4.573,0-7.254,2.415-7.254,7.917v3.323h-4.701v4.995h4.701v13.729C22.089,42.905,23.032,43,24,43c0.875,0,1.729-0.08,2.572-0.194V29.036z',
    },
    {
        id: 2,
        href: 'http://line.me/ti/p/@rs.trophy',
        fill1: '#00c300',
        d1: 'M12.5,42h23c3.59,0,6.5-2.91,6.5-6.5v-23C42,8.91,39.09,6,35.5,6h-23C8.91,6,6,8.91,6,12.5v23C6,39.09,8.91,42,12.5,42z',
        fill2: '#fff',
        d2: 'M37.113,22.417c0-5.865-5.88-10.637-13.107-10.637s-13.108,4.772-13.108,10.637c0,5.258,4.663,9.662,10.962,10.495c0.427,0.092,1.008,0.282,1.155,0.646c0.132,0.331,0.086,0.85,0.042,1.185c0,0-0.153,0.925-0.187,1.122c-0.057,0.331-0.263,1.296,1.135,0.707c1.399-0.589,7.548-4.445,10.298-7.611h-0.001C36.203,26.879,37.113,24.764,37.113,22.417z M18.875,25.907h-2.604c-0.379,0-0.687-0.308-0.687-0.688V20.01c0-0.379,0.308-0.687,0.687-0.687c0.379,0,0.687,0.308,0.687,0.687v4.521h1.917c0.379,0,0.687,0.308,0.687,0.687C19.562,25.598,19.254,25.907,18.875,25.907z M21.568,25.219c0,0.379-0.308,0.688-0.687,0.688s-0.687-0.308-0.687-0.688V20.01c0-0.379,0.308-0.687,0.687-0.687s0.687,0.308,0.687,0.687V25.219z M27.838,25.219c0,0.297-0.188,0.559-0.47,0.652c-0.071,0.024-0.145,0.036-0.218,0.036c-0.215,0-0.42-0.103-0.549-0.275l-2.669-3.635v3.222c0,0.379-0.308,0.688-0.688,0.688c-0.379,0-0.688-0.308-0.688-0.688V20.01c0-0.296,0.189-0.558,0.47-0.652c0.071-0.024,0.144-0.035,0.218-0.035c0.214,0,0.42,0.103,0.549,0.275l2.67,3.635V20.01c0-0.379,0.309-0.687,0.688-0.687c0.379,0,0.687,0.308,0.687,0.687V25.219z M32.052,21.927c0.379,0,0.688,0.308,0.688,0.688c0,0.379-0.308,0.687-0.688,0.687h-1.917v1.23h1.917c0.379,0,0.688,0.308,0.688,0.687c0,0.379-0.309,0.688-0.688,0.688h-2.604c-0.378,0-0.687-0.308-0.687-0.688v-2.603c0-0.001,0-0.001,0-0.001c0,0,0-0.001,0-0.001v-2.601c0-0.001,0-0.001,0-0.002c0-0.379,0.308-0.687,0.687-0.687h2.604c0.379,0,0.688,0.308,0.688,0.687s-0.308,0.687-0.688,0.687h-1.917v1.23H32.052z',
    },
    {
        id: 3,
        href: getRandomNumber(),
        fill1: '#0f0',
        d1: 'M13,42h22c3.866,0,7-3.134,7-7V13c0-3.866-3.134-7-7-7H13c-3.866,0-7,3.134-7,7v22	C6,38.866,9.134,42,13,42z',
        fill2: '#fff',
        d2: 'M35.45,31.041l-4.612-3.051c-0.563-0.341-1.267-0.347-1.836-0.017c0,0,0,0-1.978,1.153	c-0.265,0.154-0.52,0.183-0.726,0.145c-0.262-0.048-0.442-0.191-0.454-0.201c-1.087-0.797-2.357-1.852-3.711-3.205	c-1.353-1.353-2.408-2.623-3.205-3.711c-0.009-0.013-0.153-0.193-0.201-0.454c-0.037-0.206-0.009-0.46,0.145-0.726	c1.153-1.978,1.153-1.978,1.153-1.978c0.331-0.569,0.324-1.274-0.017-1.836l-3.051-4.612c-0.378-0.571-1.151-0.722-1.714-0.332	c0,0-1.445,0.989-1.922,1.325c-0.764,0.538-1.01,1.356-1.011,2.496c-0.002,1.604,1.38,6.629,7.201,12.45l0,0l0,0l0,0l0,0	c5.822,5.822,10.846,7.203,12.45,7.201c1.14-0.001,1.958-0.248,2.496-1.011c0.336-0.477,1.325-1.922,1.325-1.922	C36.172,32.192,36.022,31.419,35.45,31.041z',
    },
    {
        id: 4,
        href: 'mailto:ruamsukplating@gmail.com',
        fill1: '#4caf50',
        d1: 'M45,16.2l-5,2.75l-5,4.75L35,40h7c1.657,0,3-1.343,3-3V16.2z',
        fill2: '#1e88e5',
        d2: 'M3,16.2l3.614,1.71L13,23.7V40H6c-1.657,0-3-1.343-3-3V16.2z',
        fill3: '#c62828',
        d3: 'M3,12.298V16.2l10,7.5V11.2L9.876,8.859C9.132,8.301,8.228,8,7.298,8h0C4.924,8,3,9.924,3,12.298z',
        fill4: '#fbc02d',
        d4: 'M45,12.298V16.2l-10,7.5V11.2l3.124-2.341C38.868,8.301,39.772,8,40.702,8h0 C43.076,8,45,9.924,45,12.298z',
        polyfill: '#e53935',
        pointpolly:'35,11.2 24,19.45 13,11.2 12,17 13,23.7 24,31.95 35,23.7 36,17',  
    },
]
</script>

// src/components/Navigations/SocialBar.tsx
import Link from "next/link";
export const socials = [
  {
    name: "ถ้วยรางวัลราคาโรงงาน RS Trophy",
    href: "https://www.m.me/RSTrophy01",
    src: "/logo/facebook.svg",
    alt: "facebook logo",
  },
  {
    name: "@rs.trophy",
    href: "http://line.me/ti/p/@rs.trophy",
    src: "/logo/line.svg",
    alt: "line logo",
  },
  {
    name: "0649370011",
    href: "tel:0649370011",
    src: "/logo/phone.svg",
    alt: "phone logo",
  },
  {
    name: "ruamsukplating@gmail.com",
    href: "mailto:ruamsukplating@gmail.com",
    src: "/logo/gmail.svg",
    alt: "gmail logo",
  },
  {
    name: "Rs trophy ร่วมสุขถ้วยรางวัล",
    href: "https://goo.gl/maps/yNtcKifRHViNarrv6",
    src: "/logo/googlemaps.svg",
    alt: "google map logo",
  },
];

export function SocialBar() {
  return (
    <div className="mx-auto rounded-t-lg shadow bg-gray-900 sticky bottom-0 w-full py-1">
      <p className="text-center text-white">ติดต่อได้ที่</p>
      <div className="mx-auto max-w-screen-xl px-4 flex justify-center items-center w-full h-full">
        <div className="flex-shrink-0 flex items-center space-x-4 md:space-x-0">
          {socials.map((social, index) => (
            <Link
              aria-label={social.alt}
              key={index}
              href={social.href}
              target="_blank"
              rel="noopener noreferrer"
            >
              <img
                loading="lazy"
                src={social.src}
                alt={social.alt}
                width={50}
                height={50}
                className={`transition-transform duration-300 hover:scale-125 ${
                  (social.alt === "phone logo" ||
                    social.alt === "gmail logo") &&
                  "lock md:hidden"
                }`}
              />
            </Link>
          ))}
        </div>
      </div>
    </div>
  );
}
