// pages/blog/index.vue
<script setup lang="ts">
useSeoMeta({
  title: "RS AWARD | บทความ",
  description: "บทความ",
  keywords: "RS AWARD, บทความ",
});
</script>
<template>
  <h1 class="text-center p-1">บทความ</h1>
  <div>
    <ContentList
      class=""
      path="/blog"
      fields="title,thumbnail"
      :query="{
        draft: false,
        sort: [
          {
            title: -1,
          },
        ],
      }"
      v-slot="{ list }"
    >
      <div class="grid grid-cols-1 md:grid-cols-2 gap-2">
        <div
          v-for="blog in list"
          :key="blog._path"
          class="grid grid-cols-2 gap-2"
        >
          <div class="p-1">
            <NuxtLink :to="'/blog/' + blog.slug">
              <img
                v-if="blog.thumbnail"
                :src="blog.thumbnail"
                :alt="blog.title"
                :title="blog.title"
              />
            </NuxtLink>
          </div>
          <div class="my-auto p-1">
            <h3 class="text-2xl font-bold">
              <NuxtLink :to="'/blog/' + blog.slug">{{ blog.title }}</NuxtLink>
            </h3>
            <p>{{ blog.description }}</p>
            <div class="mx-auto">
              <NuxtLink :to="'/blog/' + blog.slug"
                ><button>ดูเพิ่มเติม</button></NuxtLink
              >
            </div>
          </div>
        </div>
      </div>
    </ContentList>
  </div>
</template>

// pages/blog/index.tsx
import type { Metadata } from "next";
import type { GetStaticProps, NextPage } from "next";
import { articles } from "@/components/data/blog";
import { Article } from "@/components/interface/blog"; // Adjust the path accordingly
import Link from "next/link";
interface HomeProps {
  articles: Article[];
}
export const metadata: Metadata = {
  title: "RS AWARD | บทความ",
  description:
    "บริษัทจัดจำหน่ายโล่รางวัลคุณภาพดีแข็งแรงทนทาน โดยเรามีทั้งในรูปแบบหน้าร้านและออนไลน์พร้อมบริการจัดส่งทั่วประเทศไทย",
  keywords: "RS MEDAL, โล่รางวัล",
};

const Home: NextPage<HomeProps> = ({ articles }) => {
  return (
    <div>
      <h1 className="text-center">บทความ</h1>
      <div className="grid grid-cols-1 md:grid-cols-2  gap-4">
        {articles.map((article) => (
          <Link key={article.link} href={"/blog/" + article.link}>
            <div className="grid grid-cols-2 gap-2">
              <img src="/test/1600900.png" />
              <div className="my-auto grid grid-cols-1 gap-2">
                <h2>{article.title}</h2>
                <p>{article.description}</p>
                <button className="bg-blue-500 hover:bg-blue-700 text-white font-bold p-2 rounded-full transition duration-300 ease-in-out">
                  ดูเพิ่มเติม {">"}
                </button>
              </div>
            </div>
          </Link>
        ))}
      </div>
    </div>
  );
};

export const getStaticProps: GetStaticProps<HomeProps> = async () => {
  const fetchedArticles = articles;
  return {
    props: {
      articles: fetchedArticles,
    },
  };
};
export default Home;
