// components/product.vue
<template>
    <div class="bg-white">
        <div class="mx-auto max-w-2xl px-4 py-8 sm:px-6 lg:max-w-7xl lg:px-8">
            <div class="mt-6 grid gap-x-6 gap-y-10 xl:gap-x-6 grid-cols-2 lg:grid-cols-4">
                <div v-for="product in products" :key="product.id"
                    class="group relative rounded-lg border border-gray-100 shadow-md p-4">
                    <div
                        class="aspect-h-1 aspect-w-1 w-full overflow-hidden rounded-md bg-gray-200 transition-transform duration-300 hover:scale-110">
                        <NuxtLink to="/"><img :src="product.imageSrc" :alt="product.imageAlt"
                                class="h-full w-full object-cover object-center transition-transform duration-300 hover:scale-110" />
                        </NuxtLink>

                    </div>
                    <div class="mt-4 justify-between">
                        <div>
                            <h3 class="text-lg text-gray-700">
                                <a :href="product.href">
                                    {{ product.name }}
                                </a>
                            </h3>
                        </div>
                        <div>
                            <p class="text-lg font-medium text-gray-900">฿{{ product.price }}</p>
                        </div>
                        <div>
                            <NuxtLink to="">
                                <button
                                    class="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded w-full text-sm transition-transform duration-300 hover:scale-110">
                                    ดูสินค้า
                                </button>
                            </NuxtLink>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</template>

<script setup lang="ts">
const products = [
    {
        id: 1,
        sku: 'RS 2302-3',
        name: 'โล่รางวัล RS 2302-3',
        description: 'โล่รางวัล RS 2302-3 description',
        href: '#',
        imageSrc: '/1000750.png',
        imageAlt: "Front of men's Basic Tee in black.",
        price: '1800',
    }, {
        id: 1,
        sku: 'RS 2302-3',
        name: 'โล่รางวัล RS 2302-3',
        description: 'โล่รางวัล RS 2302-3 description',
        href: '#',
        imageSrc: '/1000750.png',
        imageAlt: "Front of men's Basic Tee in black.",
        price: '1800',
    }, {
        id: 1,
        sku: 'RS 2302-3',
        name: 'โล่รางวัล RS 2302-3',
        description: 'โล่รางวัล RS 2302-3 description',
        href: '#',
        imageSrc: '/1000750.png',
        imageAlt: "Front of men's Basic Tee in black.",
        price: '1800',
    }, {
        id: 1,
        sku: 'RS 2302-3',
        name: 'โล่รางวัล RS 2302-3',
        description: 'โล่รางวัล RS 2302-3 description',
        href: '#',
        imageSrc: '/1000750.png',
        imageAlt: "Front of men's Basic Tee in black.",
        price: '1800',
    }, {
        id: 1,
        sku: 'RS 2302-3',
        name: 'โล่รางวัล RS 2302-3',
        description: 'โล่รางวัล RS 2302-3 description',
        href: '#',
        imageSrc: '/1000750.png',
        imageAlt: "Front of men's Basic Tee in black.",
        price: '1800',
    }, {
        id: 1,
        sku: 'RS 2302-3',
        name: 'โล่รางวัล RS 2302-3',
        description: 'โล่รางวัล RS 2302-3 description',
        href: '#',
        imageSrc: '/1000750.png',
        imageAlt: "Front of men's Basic Tee in black.",
        price: '1800',
    }, {
        id: 1,
        sku: 'RS 2302-3',
        name: 'โล่รางวัล RS 2302-3',
        description: 'โล่รางวัล RS 2302-3 description',
        href: '#',
        imageSrc: '/1000750.png',
        imageAlt: "Front of men's Basic Tee in black.",
        price: '1800',
    }, {
        id: 1,
        sku: 'RS 2302-3',
        name: 'โล่รางวัล RS 2302-3',
        description: 'โล่รางวัล RS 2302-3 description',
        href: '#',
        imageSrc: '/1000750.png',
        imageAlt: "Front of men's Basic Tee in black.",
        price: '1800',
    }, {
        id: 1,
        sku: 'RS 2302-3',
        name: 'โล่รางวัล RS 2302-3',
        description: 'โล่รางวัล RS 2302-3 description',
        href: '#',
        imageSrc: '/1000750.png',
        imageAlt: "Front of men's Basic Tee in black.",
        price: '1800',
    }, {
        id: 1,
        sku: 'RS 2302-3',
        name: 'โล่รางวัล RS 2302-3',
        description: 'โล่รางวัล RS 2302-3 description',
        href: '#',
        imageSrc: '/1000750.png',
        imageAlt: "Front of men's Basic Tee in black.",
        price: '1800',
    }, {
        id: 1,
        sku: 'RS 2302-3',
        name: 'โล่รางวัล RS 2302-3',
        description: 'โล่รางวัล RS 2302-3 description',
        href: '#',
        imageSrc: '/1000750.png',
        imageAlt: "Front of men's Basic Tee in black.",
        price: '1800',
    }, {
        id: 1,
        sku: 'RS 2302-3',
        name: 'โล่รางวัล RS 2302-3',
        description: 'โล่รางวัล RS 2302-3 description',
        href: '#',
        imageSrc: '/1000750.png',
        imageAlt: "Front of men's Basic Tee in black.",
        price: '1800',
    },
]
</script>

// src/components/Section/Product.tsx
import React from "react";
import { ProductProps } from "@/components/Props/Product";
import Link from "next/link";

interface ProductComponentProps {
  products: ProductProps[];
  limit?: number; // Add a limit prop with an optional number type
}

const Product: React.FC<ProductComponentProps> = ({
  products,
  limit = Infinity,
}) => {
  // Use the limit prop to slice the products array based on the specified limit
  const limitedProducts =
    limit !== Infinity ? products.slice(0, limit) : products;

  return (
    <div className="bg-white">
      <div className="mx-auto max-w-2xl lg:max-w-7xl">
        <div className="mt-6 grid grid-cols-2 gap-4 sm:grid-cols-3 md:grid-cols-4 ">
          {limitedProducts.map((product) => (
            <div
              key={product.sku}
              className="group relative transition-transform duration-300 hover:scale-105 hover:shadow-lg rounded-lg p-2"
            >
              <Link href={"/product/" + product.sku}>
                <img src="\test\1600900.png" alt={product.sku} />
              </Link>

              <div className="mt-1 flex justify-between">
                <div className="mx-auto">
                  <Link href={"/product/" + product.sku}>
                    <h2 className="text-center ">โล่รางวัล {product.sku}</h2>
                  </Link>

                  {!(
                    product.width === "" &&
                    product.length === "" &&
                    product.height === ""
                  ) && (
                    <p>
                      {product.width} x {product.length} x {product.height} mm
                    </p>
                  )}
                  {!(product.price === "") && (
                    <p className="">{product.price} บาท</p>
                  )}
                </div>
              </div>
            </div>
          ))}
        </div>
      </div>
    </div>
  );
};

export default Product;
