// pages/index.vue
<script setup lang="ts">
useSeoMeta({
  title: "RS AWARD | โล่รางวัลคริสตัล โล่อะคริลิค คุณภาพดีแข็งแรงทนทาน",
  description:
    "บริษัทจัดจำหน่ายโล่รางวัลคุณภาพดีแข็งแรงทนทาน มีให้เลือกทั้งโล่รางวัลคริสตัล โล่รางวัลอะคริลิค โดยเรามีทั้งในรูปแบบหน้าร้านและออนไลน์พร้อมบริการจัดส่งทั่วประเทศไทย",
  keywords:
    "RS AWARD, โล่รางวัล, โล่คริสตัล, โล่รางวัลคริสตัล, โล่อะคริลิค, โล่รางวัลอะคริลิค",
  ogTitle:
    "RS AWARD | จัดจำหน่าย โล่รางวัลคริสตัล โล่อะคริลิค คุณภาพดีแข็งแรงทนทาน",
  ogDescription:
    "บริษัทจัดจำหน่ายโล่รางวัลคุณภาพดีแข็งแรงทนทาน มีให้เลือกทั้งโล่รางวัลคริสตัล โล่รางวัลอะคริลิค โดยเรามีทั้งในรูปแบบหน้าร้านและออนไลน์พร้อมบริการจัดส่งทั่วประเทศไทย",
  ogImage: "/panel/hero_section.webp",
});
</script>
<template>
  <div class="relative h-full">
    <img
      src="/panel/hero_section.webp"
      class="w-full h-auto"
      alt="RS AWARD PANEL"
      title="RS AWARD PANEL"
      aria-label="RS AWARD PANEL"
      width="1278px"
      height="369px"
    />
  </div>
  <div class="mx-auto items-center gap-x-8 gap-y-16 p-2 lg:px-8">
    <div class="mx-auto max-w-4xl">
      <h2 class="text-3xl text-gray-900 sm:text-4xl mx-auto">
        RS AWARD โล่รางวัลคุณภาพดี
      </h2>
      <p class="mt-4 text-gray-500 mx-auto">
        RS AWARD บริษัทจัดจำหน่ายโล่รางวัลคุณภาพดีแข็งแรงทนทาน มีให้เลือกทั้ง
        โล่รางวัลคริสตัล โล่รางวัลอะคริลิคสำเร็จรูป โล่รางวัลอะคริลิคสั่งทำ
        พร้อมมีทีมกราฟิกดีไซน์บริการการออกแบบฟรี
        โดยเรามีทั้งในรูปแบบหน้าร้านและออนไลน์พร้อมบริการจัดส่งทั่วประเทศไทย
      </p>
    </div>
    <div class="py-4">
      <h1 class="text-center">โล่รางวัล</h1>
      <AppCategory />
      <div class="mx-auto">
        <h2 class="text-center">ผลงานที่ผ่านมา</h2>
        <div class="gap-2 grid grid-cols-3 md:grid-cols-4">
          <img
            v-for="index in 3"
            :key="index"
            :src="`/pastwork/${index}.webp`"
            width="295px"
            height="295px"
            loading="lazy"
            alt="ผลงานโล่รางวัลที่ผ่านมา"
            title="ผลงานโล่รางวัลที่ผ่านมา"
            aria-label="ผลงานโล่รางวัลที่ผ่านมา"
            class="scaleup"
          />
        </div>
      </div>
      <AppOurCustomer />
    </div>
  </div>
</template>

// pages/index.tsx
import Link from "next/link";
import type { GetStaticProps, Metadata, NextPage } from "next";
import { Article } from "@/components/interface/blog";
import { articles } from "@/components/data/blog";
import BlogPreview from "@/components/BlogPreview";
export const metadata: Metadata = {
  title:
    "RS AWARD | จัดจำหน่าย โล่รางวัลคริสตัล โล่อะคริลิค คุณภาพดีแข็งแรงทนทาน",
  description:
    "บริษัทจัดจำหน่ายโล่รางวัลคุณภาพดีแข็งแรงทนทาน มีให้เลือกทั้งโล่รางวัลคริสตัล โล่รางวัลอะคริลิค โดยเรามีทั้งในรูปแบบหน้าร้านและออนไลน์พร้อมบริการจัดส่งทั่วประเทศไทย",
  keywords:
    "RS AWARD, โล่รางวัล, โล่คริสตัล, โล่รางวัลคริสตัล, โล่อะคริลิค, โล่รางวัลอะคริลิค",
};
const images = [
  {
    name: "โล่คริสตัล",
    link: "/crystal",
    description: "",
    src: "/panel/finished_crystal.webp",
    alt: "",
  },
  {
    name: "โล่อะคริลิคสำเร็จรูป",
    link: "/acrylic/finished",
    description: "",
    src: "/panel/finished_acrylic.webp",
    alt: "",
  },
  {
    name: "โล่อะคริลิคสั่งทำ",
    link: "/acrylic/custom",
    description: "",
    src: "/panel/custom_acrylic.webp",
    alt: "",
  },
];
interface HomeProps {
  articles: Article[];
}
const Home: NextPage<HomeProps> = ({ articles }) => {
  return (
    <main>
      <div className="relative h-full">
        <img
          src="/panel/hero_section.webp"
          width="0"
          height="0"
          sizes="100vw"
          className="w-full h-auto"
          alt="RS AWARD PANEL"
          aria-label=""
        />
      </div>
      <div className="bg-white py-4">
        <div className="mx-auto items-center gap-x-8 gap-y-16 p-2 lg:px-8">
          <div className="mx-auto max-w-4xl">
            <h2 className="text-3xl text-gray-900 sm:text-4xl mx-auto">
              RS AWARD โล่รางวัลคุณภาพดี
            </h2>
            <p className="mt-4 text-gray-500 mx-auto">
              บริษัทจัดจำหน่ายโล่รางวัลคุณภาพดีแข็งแรงทนทาน
              มีให้เลือกทั้งโล่รางวัลคริสตัล โล่รางวัลอะคริลิค
              โดยเรามีทั้งในรูปแบบหน้าร้านและออนไลน์พร้อมบริการจัดส่งทั่วประเทศไทย
            </p>
          </div>
          <div className="py-4">
            <h1 className="text-center">โล่รางวัล</h1>
            <div className="grid grid-cols-2 lg:grid-cols-3 gap-4 sm:gap-6 lg:gap-8 py-2">
              {images.map((image) => (
                <div
                  className="relative h-full transition-transform duration-300 hover:scale-105"
                  key={image.name}
                >
                  <Link href={image.link}>
                    <img
                      src={image.src}
                      alt={image.alt}
                      className="w-full h-auto rounded-lg bg-gray-100 "
                      aria-label=""
                    />
                    <div className="mx-auto text-center">
                      <h2>{image.name}</h2>
                    </div>
                  </Link>
                </div>
              ))}
            </div>
          </div>
        </div>
      </div>
      <div>
        <h2 className="text-center">บทความโล่รางวัล</h2>
        <BlogPreview articles={articles} />
      </div>
    </main>
  );
};
export const getStaticProps: GetStaticProps<HomeProps> = async () => {
  const fetchedArticles = articles;
  return {
    props: {
      articles: fetchedArticles,
    },
  };
};
export default Home;
